### ISSUE TITLE
vpn vs staff SSID?

### ISSUE THREAD

**Issue by zunder1990** [socallinuxexpo/SCALE_network_public#1]
We will need a way to access the backend services and networks.  We can use a SSID on the APs and connect to the staff vlan or host an openvpn service (on pfsense?). With the vpn route staff that need access to backend services and networks would connect to one of the public SSIDs and connect using a openvpn client.

## Networks
- Wired staff network( computers and printers)
- Network management(IPs of the things like switches, routers, servers)
- AV( video network)
- Regdesk(registration computers and printers)
- Display(network for Pie's connected to tvs)

## Services
- control interfaces for switches and APs(ssh and/or http)
- ssh access to servers
- http admin access to servers/services

**staff SSID**
**Pro**
- Easier and simpler 
- No client software needed. Client only needs to connect to wireless network

**Con**
- More SSIDs=more overhead on wireless rf spectrum
- Cant tell clients apart with regards to firewall rules
- Keeping control of who has access to the staff network

**openvpn**
**Pro**
- Can make generic users based on roles with users roles getting different ip subnets. Then we can setup firewall rules based on the ip networks that was given to that vpn users. 

**Con**
- More setup and possibility more support needed

**Comment by irabinovitch** [comment]
We've historically had a staff SSID with WPA2 encryption that didn't broadcast it's SSID. It hasn't been an issue, so I think easiest is to continue that way? My main concern re: OpenVPN is that we're going to run into support / training /install issues that will suck up our time.

**Comment by zunder1990** [comment]
I agree that that a staff SSID would be easier than the openvpn mode but I think it should be broadcasted. Hidding a SSID brings no added security but does make it harder to join.

**Comment by l2ol33rt** [comment]
staff SSID :+1:

If we broadcast the SSID do you think itll cause confusion about which SSIDs to connect to for conference participants? That'd be the only reason why I could see hiding it since @zunder1990 you're right it doesnt add any additional security.

**Comment by zunder1990** [comment]
If it is called something like SCALE-staff then I dont think normal people would try to connect.
